export const COMPUTER = "COMPUTER";
export const UPDATE_REV_LIST_FUNCTION = "UPDATE_REVLIST_FUNCTION";
export const UPDATE_SELECTED_REV_FUNCTION = "UPDATE_SELECTED_REV_FUNCTION";
export const UPDATE_LOADING_FUNCTION = "UPDATE_LOADING_FUNCTION";
export const UPDATE_MESSAGES_FUNCTION = "UPDATE_MESSAGES_FUNCTION";
export const MESSAGES_KEY = "MESSAGES";
